# =============================================================================
# Authors
#
# Created by jaychowcl @ Saez-Rodriguez Group & EMBL-EBI Functional Genomics Team on May 2026
# https://github.com/jaychowcl
# https://saezlab.org
# https://www.ebi.ac.uk/about/teams/functional-genomics/
# =============================================================================
"""Versioned data model for the MINiML-compatible JSON package."""

from .model import (
    MINIML_SCHEMA_VERSION,
    AssayNode,
    AssayPath,
    Accession,
    Address,
    Channel,
    Characteristics,
    Contributor,
    DataColumn,
    Database,
    DataTable,
    FASTQFile,
    InstrumentModel,
    MINiMLModelError,
    MINiMLPackage,
    MINiMLValidationIssue,
    Organization,
    NamedComment,
    NamedValue,
    OntologyValue,
    Organism,
    Person,
    Platform,
    PubMedPublication,
    Protocol,
    ProtocolApplication,
    Reference,
    Relation,
    Repeat,
    Sample,
    Series,
    SRARun,
    Status,
    SourceDocument,
    SourceInfo,
    SupplementLink,
    TableData,
    Variable,
)
from .migration import MINiMLMigrationResult, MINiMLV1Migrator, MINiMLV2Migrator
from .harmonization import (
    HarmonizedValue,
    append_harmonized_value,
    harmonized_mapping,
    harmonized_value_mappings,
    is_harmonized_key,
    iter_harmonized_values,
    named_harmonized_rows,
    next_harmonized_index,
    parse_harmonized_key,
    parse_harmonized_mapping,
)
from .codec import (
    MINiMLBatchDecodeResult,
    MINiMLCodec,
    MINiMLCompatibilityError,
    MINiMLDecodeResult,
)

__all__ = [
    "MINIML_SCHEMA_VERSION",
    "AssayNode",
    "AssayPath",
    "Accession",
    "Address",
    "Channel",
    "Characteristics",
    "Contributor",
    "DataColumn",
    "Database",
    "DataTable",
    "FASTQFile",
    "InstrumentModel",
    "HarmonizedValue",
    "append_harmonized_value",
    "MINiMLModelError",
    "MINiMLPackage",
    "MINiMLValidationIssue",
    "Organization",
    "NamedComment",
    "NamedValue",
    "OntologyValue",
    "Organism",
    "Person",
    "Platform",
    "PubMedPublication",
    "Protocol",
    "ProtocolApplication",
    "Reference",
    "Relation",
    "Repeat",
    "Sample",
    "Series",
    "SRARun",
    "Status",
    "SourceDocument",
    "SourceInfo",
    "SupplementLink",
    "TableData",
    "Variable",
    "harmonized_mapping",
    "harmonized_value_mappings",
    "is_harmonized_key",
    "iter_harmonized_values",
    "named_harmonized_rows",
    "next_harmonized_index",
    "parse_harmonized_key",
    "parse_harmonized_mapping",
    "MINiMLBatchDecodeResult",
    "MINiMLCodec",
    "MINiMLCompatibilityError",
    "MINiMLDecodeResult",
    "MINiMLMigrationResult",
    "MINiMLV1Migrator",
    "MINiMLV2Migrator",
]
